### ISSUE TITLE
您好,作者大大

### ISSUE THREAD

**Issue by SuzukazeHaruka** [yindz/crud-generator#7]
您好,作者大大,我想请问一下,返回值类型设置的时候,如何只设置Controller,而不是Service层也进设置

**Comment by yindz** [comment]
你好，我这里之所以在Service层也设置了统一的返回值类型，是为了兼容微服务或RPC调用等场景（比如常见的Dubbo服务）才特地做的，这些场景下经常需要Service的实现类里面返回一些必要信息（如业务相关的错误信息），一般是需要借助一个基础类进行包装后返回，而不是直接返回相应对象。
对于你这种需求，我建议你直接修改模板来实现，包括 controller.ftl 以及 serviceInterface.ftl、tkServiceImpl.ftl、origServiceImpl.ftl 、mpServiceImpl.ftl等。这些模板都是标准的 Freemarker 模板，稍微改改就行了。
